### ISSUE TITLE
Issue after settings validation

### ISSUE THREAD

**Issue by juban** [kffein/craft-self-licenses-manager#1]
Hi,

After settings validation, the following exception is raised:

`Return value of kffein\pluginlicensemanager\services\PluginlicensemanagerService::getLicenses() must be an instance of kffein\pluginlicensemanager\services\object, instance of stdClass returned`

Settings do not get saved.

Craft CMS version: 3.0.37
Plugin version: 1.0.4

**Comment by jlachancekffein** [comment]
Hi,

Can I ask you which version of php you are using ?

Without knowing, I think is related to the fact that your are not using php version 7.2.

Return of type object is valid in php 7.2 but not in previous version.
https://stackoverflow.com/a/13287627

I will make the change as soon as possible to support previous versions of php.

Thanks for your notification.

**Comment by jlachancekffein** [comment]
This is now fixed for previous versions of php.

If you can run > compose update you should now have v1.0.5.

Can you confirm that it solved your problem please?

**Comment by juban** [comment]
Hi @jlachancekffein ,

Thank you for your quick support.
Indeed, we are using PHP 7.1 containers and stacks, which is not uncommon theses days.
And I think you should probably also support PHP 7.0 as it is the minimum requirement for Craft CMS 3 right now.
I will try you fix as soon as possible an let you know.

Thanks again.

**Comment by jlachancekffein** [comment]
Hi @juban ,

The last release will support 7.0 as well.

I'll wait for your reply before closing this issue.

Thank you

**Comment by juban** [comment]
Hi @jlachancekffein 

Just checked the 1.0.5 release.
Settings are saved and I can view the list of according licences now. 👍 

However, there still seem to be an issue related to licence generation.
I will open another ticket on that matter to provide enough infos.

Thanks again.
